# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8660a8c94e81f7319acbf4edac047fe2c3a06884dd4907683495d6ac4be4301fdb8111071b71a9792c995407a88a8078a052c5bcb8106ec00d3e72bb53dd1f7

test:
  secret_key_base: a1d86ffbc1d3549a49738dc44bb73c91f7239a3869f2523e7bb1191fc494108193380d897bca530866cebbc65c2f8e0c664f4c926c4575b92166b0f9498e4806

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
